name = input("Hi, I am python! What is your name?")
print ("hello, " + name + ", its nice to meet you.")
name2 = input( "Okay" + name + ", I have a few questions for you." )
print ("Okay python, What are they?")
Name3 = input("how old are you?")
print ("I am 16 turning 17.")
Name4 = input("That is cool I am 35.")
print ("Cool, what was your other question?")
Name5 = input("The other question is what grade are you in?")
print ("Great question, I am in the 11th grade.")
